[package]
name = "rust-chan-scraper"
version = "0.1.0"
authors = ["Celeo <mattboulanger@fastmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
getopts = "0.2"
rayon = "1.5.0"
reqwest = { version = "0.11.1", features = ["blocking"] }
scraper = "0.12.0"
